# deadcode configuration (stub)

severity_min: warning   # info|warning|error

include:
  - "src/**"

exclude:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.venv/**"
  - "**/migrations/**"
  - "**/tests/**"

tools:
  ast_grep:
    enabled: true
    rules_file:
      python: deadcode.rules.py.yml
      typescript: deadcode.rules.ts.yml
  vulture:
    enabled: true   # requires vulture to be installed
    extra_args: []
  ts_prune:
    enabled: true   # requires ts-prune to be installed
    extra_args: ["-s", "-i", "node_modules"]

# Future: per-rule overrides, JSON output, parallelism, language include/exclude.

